language: c
compiler:
- gcc
- clang
os:
- linux
before_install:
- sudo apt-get install libssl-dev lua5.1 liblua5.1-0 liblua5.1-0-dev automake
- sudo ln -s /usr/lib/x86_64-linux-gnu/liblua5.1.so.0 /usr/lib/liblua.so
- export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
install:
- wget -O aerospike-server.tgz http://aerospike.com/download/server/latest/artifact/tgz
- tar xvzf aerospike-server.tgz
- cp -f .travis/aerospike.conf ./aerospike-server/share/etc
- cd aerospike-server
- mkdir instance1
- ./bin/aerospike init --home instance1 --instance 1 --service-port 3000
- cd instance1
- sudo ./bin/aerospike start
- cd ..
- cd ..
- sleep 3
script:
- make
- make test
- make clean
- ./install_libev
- make EVENT_LIB=libev
- make EVENT_LIB=libev test
- make clean
- ./install_libuv
- make EVENT_LIB=libuv
- make EVENT_LIB=libuv test
notifications:
  slack:
    secure: k1GG7xFMgcLemnI0LxK0Qw2mukjmTKloHOyHI1wljer7GdOGy8icbaI6n7t1PCZ7MDYSmeQ8MFH5XbaUJT1lVkZYe1MNEsT3dpdDgAHBSk5dAu+5ZvFvoDZpRe7WS8X/mEThGgV1sQY1eKFVW8iVhVxLsSiaFPSWz1z/gGryhK4=
  hipchat:
    rooms:
      secure: LU2ZazlCBCJ/DhWZDgwfAASOy+kSxFlqu6w5KFfD42vCs7NU9+9Cs+nmxfg7OTR3QXv7+9rN+AH8w6jNqx7HYKLj4m+MVkceoyEzVoY+p/k0wx6OrcYW8KazBAuECCM8Lp6bOp56emEhizkjOhZcV7ZgwXo7Yn609OmiFDKzhkM=
  email:
  - qe-notices@aerospike.com
  - qe-notices-clients@aerospike.com
