language: c
compiler:
- gcc
- clang
os:
- linux
- osx
before_install:
- sudo apt-get install libssl-dev lua5.1 liblua5.1-0 liblua5.1-0-dev
- sudo ln -s /usr/lib/x86_64-linux-gnu/liblua5.1.so.0 /usr/lib/liblua.so
install:
- wget -O aerospike-server.tgz http://aerospike.com/download/server/latest/artifact/tgz
- tar xvzf aerospike-server.tgz
- cp -f .travis/aerospike.conf ./aerospike-server/share/etc
- cd aerospike-server
- mkdir instance1
- mkdir instance2
- ./bin/aerospike init --home instance1 --instance 1 --service-port 3000
- ./bin/aerospike init --home instance2 --instance 2 --service-port 3010
- cd instance1
- sudo ./bin/aerospike start
- cd ..
- cd instance2
- sudo ./bin/aerospike start
- cd ../..
- sleep 10
script:
- make
- make test
notifications:
  slack:
    secure: k1GG7xFMgcLemnI0LxK0Qw2mukjmTKloHOyHI1wljer7GdOGy8icbaI6n7t1PCZ7MDYSmeQ8MFH5XbaUJT1lVkZYe1MNEsT3dpdDgAHBSk5dAu+5ZvFvoDZpRe7WS8X/mEThGgV1sQY1eKFVW8iVhVxLsSiaFPSWz1z/gGryhK4=
